"""Public, reproducible example presets. Names are resolved after profiling."""

EXAMPLES = [
    {
        "id": "regression",
        "name": "Estimar un valor",
        "description": "Estima gasto mensual a partir de datos sintéticos de clientes.",
        "filename": "regression.xlsx",
        "format": "xlsx",
        "goal": "estimate_value",
        "problem_type": "regression",
        "target": {"name": "Gasto_mensual"},
        "date_column": None,
        "included_columns": ["Edad", "Ingreso_mensual", "Canal_preferido", "Antigüedad_meses"],
        "primary_metric": "mae",
        "depth": "recommended",
        "forecast_horizon": None,
        "aggregation": None,
        "parser_options": {"sheet_name": "Datos", "header_row": 0},
        "what_you_learn": "Cómo leer MAE, comparar una referencia y reconocer señal útil sin esperar perfección.",
    },
    {
        "id": "classification",
        "name": "Predecir una categoría",
        "description": "Predice Aprobado o Revisar con señal imperfecta y desbalance moderado.",
        "filename": "classification.xlsx",
        "format": "xlsx",
        "goal": "classify",
        "problem_type": "classification",
        "target": {"name": "Resultado"},
        "date_column": None,
        "included_columns": ["Ingreso_mensual", "Ratio_deuda", "Antigüedad_meses", "Canal", "Región"],
        "primary_metric": "balanced_accuracy",
        "depth": "recommended",
        "forecast_horizon": None,
        "aggregation": None,
        "parser_options": {"sheet_name": "Datos", "header_row": 0},
        "what_you_learn": "Cómo comparar clases con exactitud balanceada, F1 macro, soporte y matriz de confusión.",
    },
    {
        "id": "forecast_monthly",
        "name": "Estimar próximos meses",
        "description": "Pronostica una serie mensual continua con tendencia, estacionalidad y ruido.",
        "filename": "forecast_monthly.xlsx",
        "format": "xlsx",
        "goal": "forecast",
        "problem_type": "forecasting",
        "target": {"name": "Ventas"},
        "date_column": {"name": "Mes"},
        "included_columns": [],
        "primary_metric": "mae",
        "depth": "quick",
        "forecast_horizon": 6,
        "aggregation": "mean",
        "parser_options": {"sheet_name": "Datos", "header_row": 0},
        "what_you_learn": "La diferencia entre histórico, validación conocida y meses futuros sin valor real.",
    },
    {
        "id": "drivers",
        "name": "Entender variables útiles",
        "description": "Usa el ejemplo de regresión para medir importancia fuera del entrenamiento.",
        "filename": "regression.xlsx",
        "format": "xlsx",
        "goal": "drivers",
        "problem_type": "regression",
        "target": {"name": "Gasto_mensual"},
        "date_column": None,
        "included_columns": ["Edad", "Ingreso_mensual", "Canal_preferido", "Antigüedad_meses"],
        "primary_metric": "mae",
        "depth": "recommended",
        "forecast_horizon": None,
        "aggregation": None,
        "parser_options": {"sheet_name": "Datos", "header_row": 0},
        "what_you_learn": "Qué variables ayudaron a predecir y por qué importancia predictiva no significa causalidad.",
    },
    {
        "id": "exploration",
        "name": "Explorar la calidad de los datos",
        "description": "Revisa faltantes, duplicados, un ID y una columna constante sin entrenar.",
        "filename": "exploration.xlsx",
        "format": "xlsx",
        "goal": "explore",
        "problem_type": "exploration",
        "target": None,
        "date_column": None,
        "included_columns": [],
        "primary_metric": None,
        "depth": "quick",
        "forecast_horizon": None,
        "aggregation": None,
        "parser_options": {"sheet_name": "Datos", "header_row": 0},
        "what_you_learn": "Cómo interpretar el perfil antes de decidir si una tabla está lista para modelar.",
    },
]

BY_ID = {example["id"]: example for example in EXAMPLES}


def public_examples() -> list[dict]:
    return [dict(example) for example in EXAMPLES]
