import type { ReactNode } from 'react'
import { concepts, excelChecklist, preparationReality } from '../../education/concepts'

const External = ({ href, children }: { href: string, children: ReactNode }) => <a href={href} target="_blank" rel="noopener noreferrer">{children} ↗</a>

export function Guide() {
  const glossary = Object.values(concepts)
  return <main className="guidePage">
    <div className="pageTitle"><div><span className="eyebrow">GUÍA</span><h1>Aprende ML mientras analizas.</h1><p>Explicaciones prácticas para preparar tu tabla, elegir una pregunta y leer el resultado sin convertir métricas en promesas.</p></div></div>
    <nav className="guideIndex" aria-label="Contenido de la guía">
      {['preparar','analisis','validacion','metrica','resultados','limites','datasets','glosario'].map((id, index) => <a key={id} href={`#${id}`}>{index + 1}. {['Cómo preparar mi data','Qué análisis elegir','Entrenamiento y validación','Cómo elegir métrica','Cómo leer resultados','Qué NO demuestra','Datasets para practicar','Glosario'][index]}</a>)}
    </nav>
    <section id="preparar" className="panel"><h2>Cómo preparar mi data</h2><p><strong>Una fila debería representar una observación y cada columna una variable.</strong> Laboratorio ML no interpreta el diseño visual del Excel como información: importa la tabla.</p><ul>{excelChecklist.map(item => <li key={item}>{item}</li>)}</ul><div className="twoCol"><div><h3>Lo que sí hace</h3><ul>{preparationReality.yes.map(item => <li key={item}>{item}</li>)}</ul></div><div><h3>Lo que no hace</h3><ul>{preparationReality.no.map(item => <li key={item}>{item}</li>)}</ul></div></div><p>Si el archivo tiene varias hojas, podrás elegir cuál analizar. `.xls` antiguo no está soportado; guárdalo como `.xlsx` desde Excel.</p></section>
    <section id="analisis" className="panel"><h2>Qué análisis elegir</h2><div className="cardGrid compact">{['regression','classification','forecasting','drivers','exploration'].map(id => <article className="capCard" key={id}><h3>{concepts[id].name}</h3><p>{concepts[id].short}</p><small>{concepts[id].extended}</small></article>)}</div><p>Regresión necesita un target numérico. Clasificación necesita al menos dos categorías y soporte suficiente; el mínimo técnico no reemplaza una muestra práctica representativa. Pronóstico V1 necesita fecha mensual, target numérico, meses consecutivos y horizonte de 1 a 24; si hay varias filas por mes, debes elegir suma o promedio. Drivers necesita target y mide utilidad predictiva, no causalidad. Exploración no entrena.</p></section>
    <section id="validacion" className="panel"><h2>Entrenamiento y validación</h2><p>{concepts.training.short} {concepts.validation.short} La validación cruzada repite este proceso con varias particiones. Imputación, categorías y escalado se ajustan dentro de cada entrenamiento.</p><p><strong>Rápido</strong> prueba la referencia y el modelo lineal correspondiente: sirve para una primera revisión y toma menos tiempo. <strong>Recomendado</strong> añade Extra Trees y Random Forest: prueba más familias y tarda más, pero no garantiza un resultado mejor.</p></section>
    <section id="metrica" className="panel"><h2>Cómo elegir métrica</h2><div className="glossaryGrid">{['mae','rmse','r2','accuracy','balanced_accuracy','macro_f1'].map(id => <article key={id}><h3>{concepts[id].name}</h3><p>{concepts[id].short}</p><small>{[concepts[id].interpretation, concepts[id].range, concepts[id].warning].filter(Boolean).join(' ')}</small></article>)}</div></section>
    <section id="resultados" className="panel"><h2>Cómo leer resultados</h2><p><strong>Confiabilidad:</strong> ¿qué tan sólida fue la evaluación? No es una probabilidad. <strong>Métrica:</strong> ¿qué número usamos para comparar y en qué dirección mejora? <strong>Referencia:</strong> ¿aportó algo frente a una regla sencilla? <strong>Modelos:</strong> ¿qué se probó, cuál ganó y cómo se validó?</p><p>En regresión, error = predicho − real. En la matriz de confusión, fila = real, columna = predicho, diagonal = acierto y soporte = casos reales. En pronóstico se separan histórico, validación y futuro; el futuro todavía no tiene valor real y V1 no inventa intervalos.</p></section>
    <section id="limites" className="panel"><h2>Qué NO demuestra el laboratorio</h2><p>No demuestra causalidad, certeza ni que el patrón seguirá vigente. Una importancia alta solo describe ayuda predictiva bajo esta evaluación. La app no conoce cambios de negocio, grupos repetidos ni toda posible fuga de información. Una referencia sencilla puede ganar.</p></section>
    <section id="datasets" className="panel"><h2>Datasets para practicar</h2><p>Estos enlaces son referencias externas. La aplicación no descarga datos automáticamente ni envía datos a estos sitios; abrirlos solo abre el proveedor en otra pestaña.</p>
      <div className="datasetList">
        <article><h3><External href="https://archive.ics.uci.edu/">UCI Machine Learning Repository</External></h3><p>Repositorio clásico para practicar clasificación, regresión y otros problemas.</p><ul><li><External href="https://archive.ics.uci.edu/dataset/360/air+quality">Air Quality — dataset 360</External>: Excel `.xlsx`, sensores y calidad de aire; útil para exploración y regresión. La fuente declara CC BY 4.0. Requiere elegir target y columnas.</li><li><External href="https://archive.ics.uci.edu/dataset/275/bike+sharing+dataset">Bike Sharing — dataset 275</External>: CSV de demanda de bicicletas para regresión; CC BY 4.0.</li><li><External href="https://archive.ics.uci.edu/dataset/222/bank+marketing">Bank Marketing — dataset 222</External>: CSV con target yes/no para clasificación; CC BY 4.0.</li></ul></article>
        <article><h3><External href="https://www.openml.org/">OpenML</External></h3><p>Catálogo abierto y gratuito de datasets de machine learning con metadata. No todos funcionarán sin preparación.</p></article>
        <article><h3><External href="https://www.datosabiertos.gob.pe/">Plataforma Nacional de Datos Abiertos del Perú</External></h3><span className="tag">Muchos archivos Excel</span><p>Portal oficial peruano con gran cantidad de CSV y XLSX de entidades públicas. Normalmente tendrás que escoger hoja, identificar la tabla, decidir target y reorganizar subtotales o cabeceras.</p></article>
        <article><h3><External href="https://ourworldindata.org/">Our World in Data</External></h3><p>Series públicas con metadata y descargas que pueden abrirse en Excel. Muchas son anuales: sirven especialmente para exploración y no deben asumirse aptas para el pronóstico mensual regular de V1.</p></article>
      </div>
    </section>
    <section id="glosario" className="panel"><h2>Glosario</h2><div className="glossaryGrid">{glossary.map(item => <article key={item.name}><h3>{item.name}</h3><p>{item.short}</p>{item.warning && <small>{item.warning}</small>}</article>)}</div></section>
  </main>
}
