import { concepts, excelChecklist, preparationReality } from '../../education/concepts'
import { DataFlow } from '../../education/DataFlow'
import { PublicDatasetSuggestions } from '../../education/PublicDatasetSuggestions'

const sections = [
  ['flujo','Del Excel al modelo'],['excel','Cómo debería estar mi Excel'],['columnas','Entender columnas'],['preparar','Preparar sin modificar el original'],['objetivo','Elegir qué quiero predecir'],['variables','Variables disponibles y leakage'],['modelo','Qué es un modelo'],['validacion','Entrenamiento y validación'],['baseline','Baseline o referencia'],['comparacion','Cómo comparamos modelos'],['confirmacion','Confirmación'],['holdout','Prueba reservada'],['metrica','Métricas'],['clasificacion','Clasificación'],['regresion','Regresión'],['forecast','Pronóstico y backtesting'],['importancia','Importancia de variables'],['escenarios','Probar escenarios'],['limites','Qué NO demuestra Laboratorio ML'],['datasets','Datasets para practicar'],['glosario','Glosario'],
]

export function Guide() {
  const glossary = Object.values(concepts)
  return <main className="guidePage">
    <div className="pageTitle"><div><span className="eyebrow">GUÍA</span><h1>Aprende ML mientras analizas.</h1><p>Explicaciones prácticas conectadas con el mismo recorrido de la aplicación.</p></div></div>
    <nav className="guideIndex" aria-label="Contenido de la guía">{sections.map(([id,label],index) => <a key={id} href={`#${id}`}>{index+1}. {label}</a>)}</nav>
    <section id="flujo" className="panel"><h2>Del Excel al modelo</h2><DataFlow /><p>Primero interpretas la tabla y confirmas una versión preparada. Después eliges un objetivo para el análisis. Solo entonces se entrena y valida un modelo.</p></section>
    <section id="excel" className="panel"><h2>Cómo debería estar mi Excel</h2><p><strong>Una fila representa una observación:</strong> un caso, evento o periodo. <strong>Una columna representa una variable:</strong> una característica medida de la misma forma para todas las filas.</p><ul>{excelChecklist.map(item => <li key={item}>{item}</li>)}</ul><p>Si tienes un `.xls` antiguo, guárdalo como `.xlsx`. Laboratorio ML trabaja con una tabla: no combina tablas, no hace pivots ni reproduce Power Query.</p></section>
    <section id="columnas" className="panel"><h2>Entender mis columnas</h2><p>El tipo detectado es una sugerencia basada en el contenido. El uso indica si una columna puede ser una variable, si es un identificador o si debe ignorarse. El resultado que quieres predecir no se define aquí.</p><div className="glossaryGrid">{['observation','variable','detected_type','column_role','identifier'].map(id => <article key={id}><h3>{concepts[id].name}</h3><p>{concepts[id].short}</p></article>)}</div></section>
    <section id="preparar" className="panel"><h2>Preparar sin alterar el original</h2><p>La preparación confirma representaciones: fechas, separadores numéricos, espacios, IDs y decisiones explícitas sobre filas idénticas. La receta guarda esas decisiones, no tus datos.</p><div className="twoCol"><div><h3>Lo que sí hace</h3><ul>{preparationReality.yes.map(item => <li key={item}>{item}</li>)}</ul></div><div><h3>Lo que no hace</h3><ul>{preparationReality.no.map(item => <li key={item}>{item}</li>)}</ul></div></div><p>Los valores extremos pueden ser errores o casos reales importantes; se revisan en el archivo y no se eliminan automáticamente. Los filtros seguros apartan filas según condiciones explícitas. La unificación de categorías cambia etiquetas confirmadas una por una; no es un join ni fuzzy matching.</p></section>
    <section id="objetivo" className="panel"><h2>Elegir qué quiero predecir</h2><p>El resultado que quieres predecir suele llamarse <em>target</em>. Elegirlo define qué filas tienen un resultado conocido y qué evaluación corresponde. Las filas sin ese resultado siguen en el Excel preparado; solo quedan fuera de ese análisis.</p><div className="cardGrid compact">{['regression','classification','forecasting','drivers','exploration'].map(id => <article className="capCard" key={id}><h3>{concepts[id].name}</h3><p>{concepts[id].short}</p><small>{concepts[id].extended}</small></article>)}</div><p>En un pronóstico, resumir por suma o promedio pertenece al análisis y no modifica el Excel preparado anterior.</p></section>
    <section id="variables" className="panel"><h2>Qué información puede usar un modelo</h2><p>Usa solo información que existiría cuando hagas la predicción real. Si quieres predecir retrasos antes de que ocurran, la fecha programada puede existir, pero la fecha real de llegada todavía no. Usarla revelaría el futuro: eso es una fuga de información.</p></section>
    <section id="modelo" className="panel"><h2>Qué es un modelo</h2><p>Un modelo es una regla aprendida con ejemplos. Cada candidato intenta aprender de una forma distinta; todos deben competir con las mismas separaciones y contra una referencia sencilla.</p><div className="glossaryGrid">{['model','candidate','ridge','logistic_regression','extra_trees','random_forest'].map(id=><article key={id}><h3>{concepts[id].name}</h3><p>{concepts[id].short}</p></article>)}</div></section>
    <section id="validacion" className="panel"><h2>Entrenamiento, validación y prueba</h2><p>{concepts.training.short} {concepts.validation.short} Antes de empezar, la app congela las filas o periodos de cada prueba. Imputación, categorías, escalado y descarte de constantes se ajustan dentro de cada entrenamiento, sin mirar su validación. Los duplicados exactos se conservan juntos.</p><p><strong>Rápido</strong> compara las familias esenciales. <strong>Recomendado</strong> añade árboles y, en pronóstico, Holt y Holt-Winters. Probar más modelos no garantiza un resultado mejor. Un candidato aprendido solo desplaza a la referencia si mejora lo suficiente y de forma consistente en al menos tres pruebas; una diferencia pequeña favorece el método más simple.</p><p>Con soporte suficiente se aparta una prueba final antes de comparar. La elección se cierra sin verla. Si después rinde peor allí, se informa y no se cambia el ganador. En pronóstico, cada prueba histórica simula estar en una fecha pasada y usa solo el prefijo disponible.</p></section>
    <section id="baseline" className="panel"><h2>Baseline o referencia</h2><p>La referencia es una regla que <strong>no aprende nada</strong> y sirve de vara de medir: si un modelo complejo no la supera con claridad, no está aportando. Responde cuánto se logra sin esfuerzo.</p><ul><li><strong>Números:</strong> predice siempre la mediana de los datos de entrenamiento (cuando la métrica es MAE) o el promedio (RMSE y R²).</li><li><strong>Categorías:</strong> predice siempre la clase más frecuente.</li><li><strong>Series mensuales:</strong> repite el último valor conocido.</li></ul><p>Ninguna de estas reglas usa las demás variables. Puede ganar legítimamente si la complejidad no aporta una mejora suficiente.</p></section>
    <section id="comparacion" className="panel"><h2>Cómo comparamos modelos</h2><p>Primero se construyen y comparten las separaciones; después cada modelo y la referencia se miden con <strong>la misma métrica</strong>, solo sobre datos que no usaron para aprender. «Mejor» significa menos error (MAE, RMSE) o más acierto (exactitud, F1, R²) que la referencia. Para reemplazarla, un modelo debe cumplir las tres condiciones:</p><ol className="metricChecklist"><li><strong>Mejora suficiente:</strong> en MAE o RMSE, al menos 3 % menos error que la referencia; en exactitud, exactitud balanceada, F1 macro o R², al menos 0,02 más.</li><li><strong>Mejora consistente:</strong> gana en al menos 6 de cada 10 pruebas (hace falta un mínimo de 3) y la mediana de las diferencias es a su favor. Un promedio ayudado por una sola prueba no basta.</li><li><strong>Simplicidad:</strong> si varios quedan prácticamente empatados (a menos de 1 % del error de la referencia, o de 0,005 en exactitud y F1, o de 0,01 en R²), gana el más sencillo.</li></ol><p>Si ninguno las cumple, se conserva la referencia. Un candidato incompleto, fallido o con tiempo agotado no puede ganar. Los umbrales son reglas conservadoras del producto, no una prueba de significancia estadística.</p></section>
    <section id="confirmacion" className="panel"><h2>Confirmación</h2><p>Cuando el modo recomendado encuentra un ganador aprendido y hay soporte suficiente, repetimos solo ese candidato y la referencia con tres separaciones reproducibles nuevas. Si la mejora no vuelve a aparecer con suficiente consistencia, se conserva la referencia.</p></section>
    <section id="holdout" className="panel"><h2>Prueba reservada</h2><p>La prueba reservada no participa en tuning ni selección. Se abre después de congelar el ganador para comprobar si la mejora se repite. Su resultado se informa, pero nunca se usa para elegir otro modelo.</p></section>
    <section id="metrica" className="panel"><h2>Elegir y comparar una métrica</h2><p><strong>Un número aislado no permite decir “está bien” o “está mal”.</strong> Primero usa la misma métrica y las mismas observaciones para comparar el modelo con una referencia sencilla. Después contrasta el error con lo que tu decisión real puede tolerar y revisa si la mejora fue consistente.</p><ol className="metricChecklist"><li><strong>Dirección:</strong> confirma si más alto o más bajo es mejor.</li><li><strong>Referencia:</strong> compara contra una regla sencilla evaluada en los mismos casos.</li><li><strong>Escala real:</strong> en MAE y RMSE, interpreta el número en la unidad del resultado.</li><li><strong>Estabilidad:</strong> una diferencia aislada no basta; revisa particiones, confirmación y prueba reservada.</li></ol><div className="glossaryGrid">{['mae','rmse','r2','accuracy','balanced_accuracy','macro_f1'].map(id => <article key={id}><h3>{concepts[id].name}</h3><p>{concepts[id].short}</p><small>{[concepts[id].interpretation,concepts[id].range,concepts[id].compareAgainst,concepts[id].goodBad,concepts[id].warning].filter(Boolean).join(' ')}</small></article>)}</div></section>
    <section id="clasificacion" className="panel"><h2>Clasificación</h2><p>La matriz de confusión cruza categoría real por fila y predicha por columna. Exactitud balanceada y F1 macro evitan que la clase mayoritaria oculte por completo a las demás. Soporte, precisión y cobertura se leen por clase; una cobertura cero con casos suficientes merece una advertencia explícita.</p></section>
    <section id="regresion" className="panel"><h2>Regresión</h2><p>MAE resume el error absoluto medio; RMSE da más peso a errores grandes y R² compara frente a predecir el promedio. La mediana y el P90 del error absoluto describen el error típico y el extremo frecuente, pero no cambian la selección.</p></section>
    <section id="forecast" className="panel"><h2>Pronóstico y backtesting</h2><p>Cada prueba histórica simula estar en un origen pasado y solo ve su prefijo. Se revisa también cómo cambia el error del mes +1 al horizonte final. Una curva plana puede ser el resultado correcto si Último valor fue quien cumplió mejor las reglas.</p></section>
    <section id="importancia" className="panel"><h2>Importancia de variables</h2><p>La importancia por permutación altera una variable en validación y observa cuánto cambia el rendimiento. Positivo sugiere información útil; cerca de cero, poco cambio; negativo puede indicar ruido o inestabilidad. Nunca demuestra causalidad.</p></section>
    <section id="escenarios" className="panel"><h2>Probar escenarios</h2><p>En una regresión o clasificación nueva, la app reajusta localmente el modelo ya seleccionado y guarda una copia acotada para experimentar. Puedes mover hasta ocho variables importantes dentro de sus rangos observados y ver cómo cambia la proyección del resultado.</p><p><strong>La curva no se fuerza a ser lineal.</strong> En “Automático recomendado” compiten referencia, modelo lineal, Extra Trees y Random Forest usando los mismos splits. La política elige por error fuera del entrenamiento y consistencia; no por la correlación que se vea más alta. Si gana Ridge, la sensibilidad numérica será lineal porque esa es la forma del modelo ganador. Si gana un árbol, puede mostrar umbrales, mesetas, interacciones o cambios de dirección.</p><p>En pronóstico, esta pestaña permite recorrer los meses futuros ya calculados y comparar cada uno con el error histórico de ese horizonte. No modifica la serie, no recalcula el futuro y no inventa drivers externos que el modelo no recibió.</p><p>Este apartado responde “¿qué proyecta este modelo con estas entradas o para este mes?”. No vuelve a evaluar la corrida, no cambia al ganador, no ajusta hiperparámetros y no demuestra causalidad. Un resultado fuera del contexto o del periodo observado puede no ser confiable.</p></section>
    <section id="limites" className="panel"><h2>Qué NO puede hacer Laboratorio ML</h2><p>No conoce tus reglas de negocio, no demuestra causalidad o certeza y no sabe si un patrón seguirá vigente. No combina tablas, no reproduce Power Query, no elimina outliers automáticamente y no resuelve validaciones por grupos o usos temporales tabulares. Preparar datos no equivale a una limpieza perfecta.</p></section>
    <section id="datasets" className="panel"><h2>Datasets para practicar</h2><PublicDatasetSuggestions /></section>
    <section id="glosario" className="panel"><h2>Glosario</h2><div className="glossaryGrid">{glossary.map(item => <article key={item.name}><h3>{item.name}</h3><p>{item.short}</p>{item.warning && <small>{item.warning}</small>}</article>)}</div></section>
  </main>
}
