import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { api, Job } from '../../api/client'

const stages=['prepare','fit','compare','evaluate','explain','freeze_result','finished']
export function Progress(){const {runId}=useParams();const [params]=useSearchParams();const nav=useNavigate();const jobId=params.get('job')??'';const [job,setJob]=useState<Job|null>(null);const [elapsed,setElapsed]=useState(0);const [error,setError]=useState('')
 useEffect(()=>{const started=Date.now();const tick=setInterval(()=>setElapsed(Math.floor((Date.now()-started)/1000)),1000);const poll=setInterval(async()=>{try{const j=await api<Job>(`/jobs/${jobId}`);setJob(j);if(j.status==='succeeded'){clearInterval(poll);setTimeout(()=>nav(`/runs/${runId}`),500)}if(['failed','cancelled','interrupted'].includes(j.status)){clearInterval(poll);setError(j.error_code??j.status)}}catch{setError('Perdimos la conexión. El análisis puede seguir ejecutándose; estamos recuperándola.') }},1000);return()=>{clearInterval(tick);clearInterval(poll)}},[jobId,nav,runId])
 const current=Math.max(0,stages.indexOf(job?.progress.stage??'prepare'));async function cancel(){await api(`/jobs/${jobId}/cancel`,{method:'POST'});setError('Cancelación solicitada. Conservaremos cualquier resultado ya congelado.')}
 return <main className="progressPage"><section className="progressHero"><span className="eyebrow">ANÁLISIS EN CURSO</span><h1>Estamos probando qué patrón se sostiene.</h1><p>No recargues por obligación: el trabajo continúa aunque cierres esta pestaña.</p><div className="time"><strong>{Math.floor(elapsed/60).toString().padStart(2,'0')}:{(elapsed%60).toString().padStart(2,'0')}</strong><span>tiempo transcurrido · sin ETA inventada</span></div></section>{error&&<div className="alert warning"><strong>Estado</strong><span>{error}</span></div>}<section className="panel timeline"><div className="liveLine"><span className="pulse"/><div><strong>{job?.progress.message??'Preparando el análisis…'}</strong><small>Última actividad recibida ahora</small></div>{job?.progress.total_units?<span>{job.progress.completed_units} de {job.progress.total_units}</span>:null}</div><ol>{stages.slice(0,-1).map((s,i)=><li className={i<current?'done':i===current?'active':''} key={s}><span>{i<current?'✓':i+1}</span><div><strong>{['Preparar variables','Probar modelos','Comparar evidencia','Evaluar resultado','Explicar límites','Congelar resultado'][i]}</strong><small>{i<current?'Completado':i===current?'En curso':'Pendiente'}</small></div></li>)}</ol></section><div className="footerActions"><Link className="button secondary" to="/history">Ver historial</Link><button className="button danger" onClick={cancel} disabled={!job||!['queued','running'].includes(job.status)}>Cancelar análisis</button></div></main>}

